Repository RocketChat/fuselage, pull requests merged in 2020-02, with the labels that each got.

#136 fix: Replace eval-based source maps
  packages/fuselage-ui-kit/webpack.config.js
  packages/fuselage/webpack.config.js
  packages/ui-kit/webpack.config.js
Labels: ➕ Enhancement

#147 feat: Loading Component
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Loading_Default_Story.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Loading_Disabled.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Loading_Inside_Button.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Loading_Inside_Button_Inherit_Color.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Loading_States.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Loading_Default_Story.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Loading_Disabled.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Loading_Inside_Button.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Loading_Inside_Button_Inherit_Color.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Loading_States.png
  packages/fuselage/src/components/Loading/index.js
  packages/fuselage/src/components/Loading/stories.mdx
  packages/fuselage/src/components/Loading/styles.scss
  packages/fuselage/src/components/index.js
  packages/fuselage/src/components/index.scss
Labels: 🧩Component

#151 fix: Changed accordion item title proptype
  packages/fuselage/src/components/Accordion/Item.js
Labels: 🐛 Bug

#148 fix: Display name and prop types of Throbber component
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Throbber_Default_Story.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Throbber_Disabled.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Throbber_Inside_Button.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Throbber_Inside_Button_Inherit_Color.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Throbber_States.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Throbber_Default_Story.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Throbber_Disabled.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Throbber_Inside_Button.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Throbber_Inside_Button_Inherit_Color.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Throbber_States.png
  packages/fuselage/src/components/Throbber/index.js
  packages/fuselage/src/components/Throbber/stories.mdx
  packages/fuselage/src/components/Throbber/styles.scss
  packages/fuselage/src/components/index.js
  packages/fuselage/src/components/index.scss
Labels: 🐛 Bug
