Repository RocketChat/fuselage, pull requests merged in 2020-03, with the labels that each got.

#156 feat: useMutableCallback
  packages/fuselage-hooks/.jest/helpers.js
  packages/fuselage-hooks/README.md
  packages/fuselage-hooks/package.json
  packages/fuselage-hooks/src/index.js
  packages/fuselage-hooks/src/useMutableCallback.js
  packages/fuselage-hooks/tests/useClassName.spec.js
  packages/fuselage-hooks/tests/useDebouncedCallback.spec.js
  packages/fuselage-hooks/tests/useDebouncedUpdates.spec.js
  packages/fuselage-hooks/tests/useExclusiveBooleanProps.spec.js
  packages/fuselage-hooks/tests/useMediaQuery.spec.js
  packages/fuselage-hooks/tests/useMergedRefs.spec.js
  packages/fuselage-hooks/tests/useMutableCallback.spec.js
  packages/fuselage-hooks/tests/useToggle.spec.js
  packages/fuselage-hooks/tests/useUniqueId.spec.js
Labels: ⚛️ Hooks

#154 perf: Avoid re-renders due to PropsContext
  lerna-debug.log
  packages/fuselage/src/components/Box/AnimatedVisibility/index.js
  packages/fuselage/src/components/Box/Flex/index.js
  packages/fuselage/src/components/Box/Margins/index.js
  packages/fuselage/src/components/Box/PropsContext.js
  packages/fuselage/src/components/Box/Scrollable/index.js
  packages/fuselage/src/components/Box/index.js
  packages/fuselage/src/components/ButtonGroup/index.js
  packages/fuselage/src/hooks/index.js
  packages/fuselage/src/hooks/useProps.js
  packages/fuselage/src/hooks/useStyleSheet.js
Labels: ➕ Enhancement

#166 fix: Build @rocket.chat/css-in-js as ES module
  packages/css-in-js/package.json
  packages/css-in-js/rollup.config.js
  packages/fuselage/package.json
Labels: 🐛 Bug

#121 feat: Tooltip component
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Tooltips_Arrow_Positioning.png
  packages/fuselage/.loki/reference/chrome_iphone7_Misc_Tooltips_Default_Story.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Tooltips_Arrow_Positioning.png
  packages/fuselage/.loki/reference/chrome_laptop_Misc_Tooltips_Default_Story.png
  packages/fuselage/src/components/Tooltip/index.js
  packages/fuselage/src/components/Tooltip/stories.mdx
  packages/fuselage/src/components/Tooltip/styles.scss
  packages/fuselage/src/components/index.js
  packages/fuselage/src/components/index.scss
  packages/fuselage/src/styles/variables/all.scss
  packages/fuselage/src/styles/variables/borders.scss
  packages/fuselage/src/styles/variables/tooltip.scss
Labels: 🧩Component

#165 feat: Focus visible
  packages/fuselage-polyfills/index.js
  packages/fuselage-polyfills/package.json
  packages/fuselage/.storybook/config.js
  packages/fuselage/package.json
  packages/fuselage/src/components/Button/stories.mdx
  packages/fuselage/src/components/Button/styles.scss
  packages/fuselage/src/components/Tabs/index.js
  packages/fuselage/src/components/Tabs/styles.scss
  packages/fuselage/src/styles/mixins/states.scss
  packages/fuselage/src/styles/primitives/button.scss
  yarn.lock
Labels: ➕ Enhancement, 💅 Styles

#176 fix: Spacing and markup in Ui Kit inputs
  packages/fuselage-ui-kit/src/Input.js
Labels: 🐛 Bug, 💅 Styles
